linters:
    flake8:
        enable: true
        ignore: F401,E226,I101,I100,E741
    shellcheck:
        shell: bash
    csslint:
        enable: false
files:
    ignore: ['versioneer.py', 'wavefd/_version.py', 'doc/conf.py']
